---
title: "git_00"
author: "Audrea Pena"
date: "August 18, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
 "You are old, father William," the young man said,  
    "And your hair has become very white;  
  And yet you incessantly stand on your head —  
    Do you think, at your age, it is right?"  
  
  "In my youth," father William replied to his son,  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Nature’s first green is gold,  
Her hardest hue to hold.  
Her early leaf’s a flower;  
But only so an hour.  
Then leaf subsides to leaf.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.
      
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I measure every Grief I meet  
With narrow, probing, eyes –  
I wonder if It weighs like Mine –   
Or has an Easier size.  

  
I wonder if They bore it long –   
Or did it just begin –  
I could not tell the Date of Mine –   
It feels so old a pain -   

  
I wonder if it hurts to live –   
And if They have to try –   
And whether – could They choose between –   
It would not be – to die –   
  
I note that Some – gone patient long – 
At length, renew their smile –  
An imitation of a Light
That has so little Oil – 

I wonder if when Years have piled –  
Some Thousands – on the Harm –  
That hurt them early – such a lapse
Could give them any Balm –  